// Generated by Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
#ifndef PAYMENTSDKPROXY_SWIFT_H
#define PAYMENTSDKPROXY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PaymentSDK;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PaymentSDKProxy",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSString;

SWIFT_CLASS("_TtC15PaymentSDKProxy24AlternativePaymentMethod")
@interface AlternativePaymentMethod : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull unionPay;)
+ (NSString * _Nonnull)unionPay SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull stcPay;)
+ (NSString * _Nonnull)stcPay SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull valu;)
+ (NSString * _Nonnull)valu SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull meezaQR;)
+ (NSString * _Nonnull)meezaQR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull omannet;)
+ (NSString * _Nonnull)omannet SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull knetCredit;)
+ (NSString * _Nonnull)knetCredit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull knetDebit;)
+ (NSString * _Nonnull)knetDebit SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull fawry;)
+ (NSString * _Nonnull)fawry SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy21PaymentBillingDetails")
@interface PaymentBillingDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable addressLine;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable countryCode;
@property (nonatomic, copy) NSString * _Nullable zip;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PaymentTransactionDetails;
@class UIViewController;

SWIFT_PROTOCOL("_TtP15PaymentSDKProxy15PaymentCallback_")
@protocol PaymentCallback
- (void)paymentManagerWithDidFinishTransaction:(PaymentTransactionDetails * _Nullable)transactionDetails error:(NSError * _Nullable)error;
- (void)paymentManagerWithDidCancelPayment:(NSError * _Nullable)error;
- (void)paymentManagerWithDidStartPaymentTransaction:(UIViewController * _Nonnull)rootViewController;
@end

@class NSNumber;
@class PaymentTheme;
@class PaymentShippingDetails;

SWIFT_CLASS("_TtC15PaymentSDKProxy20PaymentConfiguration")
@interface PaymentConfiguration : NSObject
@property (nonatomic, copy) NSString * _Nonnull profileID;
@property (nonatomic, copy) NSString * _Nonnull serverKey;
@property (nonatomic, copy) NSString * _Nonnull clientKey;
@property (nonatomic, copy) NSString * _Nullable transactionType;
@property (nonatomic, copy) NSString * _Nullable transactionClass;
@property (nonatomic, copy) NSString * _Nonnull cartID;
@property (nonatomic, copy) NSString * _Nonnull currency;
@property (nonatomic) double amount;
@property (nonatomic, copy) NSString * _Nonnull cartDescription;
@property (nonatomic, copy) NSString * _Nullable languageCode;
@property (nonatomic, strong) PaymentTheme * _Nullable theme;
@property (nonatomic) BOOL forceShippingInfo;
@property (nonatomic) BOOL showBillingInfo;
@property (nonatomic) BOOL showShippingInfo;
@property (nonatomic, strong) PaymentBillingDetails * _Nullable billingDetails;
@property (nonatomic, strong) PaymentShippingDetails * _Nullable shippingDetails;
@property (nonatomic, copy) NSString * _Nullable merchantApplePayIdentifier;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable paymentNetworks;
@property (nonatomic, copy) NSString * _Nonnull merchantCountryCode;
@property (nonatomic, copy) NSString * _Nullable serverIP;
@property (nonatomic) NSInteger tokeniseType;
@property (nonatomic, copy) NSString * _Nonnull tokenFormat;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable transactionReference;
@property (nonatomic, copy) NSString * _Nullable screenTitle;
@property (nonatomic, copy) NSString * _Nullable merchantName;
@property (nonatomic) BOOL hideCardScanner;
@property (nonatomic) BOOL simplifyApplePayValidation;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable alternativePaymentMethods;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy20PaymentInfoViewModel")
@interface PaymentInfoViewModel : NSObject
@property (nonatomic, copy) NSString * _Nullable cardType;
@property (nonatomic, copy) NSString * _Nullable cardScheme;
@property (nonatomic, copy) NSString * _Nullable paymentDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy22PaymentResultViewModel")
@interface PaymentResultViewModel : NSObject
@property (nonatomic, copy) NSString * _Nullable responseStatus;
@property (nonatomic, copy) NSString * _Nullable responseCode;
@property (nonatomic, copy) NSString * _Nullable responseMessage;
@property (nonatomic, copy) NSString * _Nullable transactionTime;
@property (nonatomic, copy) NSString * _Nullable acquirerMessage;
@property (nonatomic, copy) NSString * _Nullable acquirerRRN;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy15PaymentSDKProxy")
@interface PaymentSDKProxy : NSObject
- (void)startCardPaymentWithConfiguration:(PaymentConfiguration * _Nonnull)configuration deleagte:(id <PaymentCallback> _Nonnull)deleagte;
- (void)startApplePayPaymentWithConfiguration:(PaymentConfiguration * _Nonnull)configuration deleagte:(id <PaymentCallback> _Nonnull)deleagte;
- (void)startAlternativePaymentMehtodWithConfiguration:(PaymentConfiguration * _Nonnull)configuration deleagte:(id <PaymentCallback> _Nonnull)deleagte;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class PaymentSDKTransactionDetails;

@interface PaymentSDKProxy (SWIFT_EXTENSION(PaymentSDKProxy)) <PaymentManagerDelegate>
- (void)paymentManagerWithDidFinishTransaction:(PaymentSDKTransactionDetails * _Nullable)transactionDetails error:(NSError * _Nullable)error;
- (void)paymentManagerWithDidCancelPayment:(NSError * _Nullable)error;
- (void)paymentManagerWithDidStartPaymentTransaction:(UIViewController * _Nonnull)rootViewController;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy22PaymentShippingDetails")
@interface PaymentShippingDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable addressLine;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable countryCode;
@property (nonatomic, copy) NSString * _Nullable zip;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
@class UIColor;
@class UIFont;

SWIFT_CLASS("_TtC15PaymentSDKProxy12PaymentTheme")
@interface PaymentTheme : NSObject
@property (nonatomic, strong) UIImage * _Nullable logoImage;
@property (nonatomic, strong) UIColor * _Nullable primaryColor;
@property (nonatomic, strong) UIColor * _Nullable primaryFontColor;
@property (nonatomic, strong) UIFont * _Nullable primaryFont;
@property (nonatomic, strong) UIColor * _Nullable secondaryColor;
@property (nonatomic, strong) UIColor * _Nullable secondaryFontColor;
@property (nonatomic, strong) UIFont * _Nullable secondaryFont;
@property (nonatomic, strong) UIColor * _Nullable strokeColor;
@property (nonatomic, strong) NSNumber * _Nullable strokeThinckness;
@property (nonatomic, strong) NSNumber * _Nullable inputsCornerRadius;
@property (nonatomic, strong) UIColor * _Nullable buttonColor;
@property (nonatomic, strong) UIColor * _Nullable buttonFontColor;
@property (nonatomic, strong) UIFont * _Nullable buttonFont;
@property (nonatomic, strong) UIColor * _Nullable titleFontColor;
@property (nonatomic, strong) UIFont * _Nullable titleFont;
@property (nonatomic, strong) UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) UIColor * _Nullable placeholderColor;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy25PaymentTransactionDetails")
@interface PaymentTransactionDetails : NSObject
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable transactionReference;
@property (nonatomic, copy) NSString * _Nullable transactionType;
@property (nonatomic, copy) NSString * _Nullable cartID;
@property (nonatomic, copy) NSString * _Nullable cartDescription;
@property (nonatomic, copy) NSString * _Nullable cartCurrency;
@property (nonatomic, copy) NSString * _Nullable cartAmount;
@property (nonatomic, strong) PaymentResultViewModel * _Nullable paymentResult;
@property (nonatomic, strong) PaymentInfoViewModel * _Nullable paymentInfo;
@property (nonatomic, strong) PaymentBillingDetails * _Nullable billingDetails;
@property (nonatomic, strong) PaymentShippingDetails * _Nullable shippingDetails;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy11TokenFormat")
@interface TokenFormat : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull none;)
+ (NSString * _Nonnull)none SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull hex32;)
+ (NSString * _Nonnull)hex32 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull alphaNum20;)
+ (NSString * _Nonnull)alphaNum20 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull digit22;)
+ (NSString * _Nonnull)digit22 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull digit16;)
+ (NSString * _Nonnull)digit16 SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull alphaNum32;)
+ (NSString * _Nonnull)alphaNum32 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy12TokeniseType")
@interface TokeniseType : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger none;)
+ (NSInteger)none SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger merchantMandatory;)
+ (NSInteger)merchantMandatory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger userMandatory;)
+ (NSInteger)userMandatory SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger userOptinoal;)
+ (NSInteger)userOptinoal SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy16TransactionClass")
@interface TransactionClass : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ecom;)
+ (NSString * _Nonnull)ecom SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull recur;)
+ (NSString * _Nonnull)recur SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15PaymentSDKProxy15TransactionType")
@interface TransactionType : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sale;)
+ (NSString * _Nonnull)sale SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull authorize;)
+ (NSString * _Nonnull)authorize SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
